---
SiteHeading: Singpost Demo
CompanyName: Demo Company
CompanyDomain: example.com
CompanyUrl: https://example.com
Rows:
- Cols:
  - Blocks:
    - Heading: Main
      Links:
      - Title: Gitlab
        URL: https://example.com
      - Title: Stand up (Google Meet)
        URL: https://example.com
      - Title: Mail
        URL: https://example.com
    - Heading: CRM
      Links:
      - Title: New Deals
        URL: https://example.com
      - Title: Ongoing Deals
        URL: https://example.com
      - Title: Archive
        URL: https://example.com
  - Blocks:
    - Heading: Kubernetes
      Links:
      - Title: ArgoCD (prod)
        URL: https://example.com
      - Title: ArgoCD (dev)
        URL: https://example.com
    - Heading: Monitoring
      Links:
      - Title: Grafana
        URL: https://example.com
      - Title: Grafana (prod)
        URL: https://example.com
      - Title: Grafana (dev)
        URL: https://example.com
    - Heading: Logs
      Links:
      - Title: Kibana (prod)
        URL: https://example.com
      - Title: Kibana (dev)
        URL: https://example.com
    - Heading: Minio
      Links:
      - Title: Minio (prod)
        URL: https://example.com
      - Title: Minio (dev)
        URL: https://example.com
  - Blocks:
    - Heading: Providers & Clouds
      Links:
      - Title: Google Admin
        URL: https://example.com
      - Title: AWS
        URL: https://example.com
      - Title: Azure
        URL: https://example.com
